amcl:
  ros__parameters:
    use_sim_time: false
    base_frame_id: base_link
    odom_frame_id: odom
    global_frame_id: map

bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 5.0

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: /app/ros2/maps/residential_map.yaml
